sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_0c66a4739110_key -iv $encrypted_0c66a4739110_iv -in service-account.json.json.enc -out service-account.json.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud component update kubectl
  - gcloud auth activate-service-account --key-file service-account.json.json
  - gcloud config set project multi-k8s-292320
  - gcloud config set compute/zone us-central1-c
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t yesha123/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true yesha123/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master

 